const projects={taskflow:{title:'TaskFlow',kicker:'Centro operativo',description:'Una plataforma integral para organizar tareas, proyectos y flujos de trabajo con claridad, seguimiento y automatizaciones.',features:['Vistas adaptables para cada equipo','Automatizaciones y recordatorios','Reportes para decidir más rápido']},gestor:{title:'Gestor de Tareas',kicker:'Gestión colaborativa',description:'Una experiencia simple y visual para organizar el trabajo diario, coordinar equipos y mantener prioridades bajo control.',features:['Panel claro con métricas clave','Seguimiento por estado y prioridad','Equipos, fechas y actividad en un solo lugar']}};
const tabs=[...document.querySelectorAll('[data-project]')];
function setProject(key){const p=projects[key];if(!p)return;tabs.forEach(t=>{const on=t.dataset.project===key;t.classList.toggle('active',on);t.setAttribute('aria-selected',String(on))});document.querySelectorAll('[data-preview]').forEach(v=>v.classList.toggle('hidden',v.dataset.preview!==key));document.querySelector('#project-title').textContent=p.title;document.querySelector('#project-kicker').textContent=p.kicker;document.querySelector('#project-description').textContent=p.description;document.querySelector('#project-features').innerHTML=p.features.map(x=>`<li>${x}</li>`).join('')}
tabs.forEach(t=>{['mouseenter','focus','click'].forEach(e=>t.addEventListener(e,()=>setProject(t.dataset.project))) });
const header=document.querySelector('#header'),menu=document.querySelector('#menu'),nav=document.querySelector('#nav');
addEventListener('scroll',()=>header.classList.toggle('scrolled',scrollY>12),{passive:true});
menu.addEventListener('click',()=>{const open=nav.classList.toggle('open');menu.setAttribute('aria-expanded',String(open))});
nav.querySelectorAll('a').forEach(a=>a.addEventListener('click',()=>{nav.classList.remove('open');menu.setAttribute('aria-expanded','false')}));
const links=[...nav.querySelectorAll('a')];
new IntersectionObserver(entries=>entries.forEach(e=>{if(e.isIntersecting)links.forEach(a=>a.classList.toggle('active',a.getAttribute('href')===`#${e.target.id}`))}),{rootMargin:'-35% 0px -55% 0px'}).observe(document.querySelector('#inicio'));
document.querySelectorAll('main section[id]').forEach(s=>new IntersectionObserver(entries=>entries.forEach(e=>{if(e.isIntersecting)links.forEach(a=>a.classList.toggle('active',a.getAttribute('href')===`#${e.target.id}`))}),{rootMargin:'-35% 0px -55% 0px'}).observe(s));
const reveal=new IntersectionObserver(entries=>entries.forEach(e=>{if(e.isIntersecting){e.target.classList.add('visible');reveal.unobserve(e.target)}}),{threshold:.1});document.querySelectorAll('.reveal').forEach(x=>reveal.observe(x));
document.querySelector('#contact-form').addEventListener('submit',e=>{e.preventDefault();const d=new FormData(e.currentTarget),name=String(d.get('name')||'').trim(),email=String(d.get('email')||'').trim(),message=String(d.get('message')||'').trim(),subject=encodeURIComponent(`Consulta de proyecto — ${name}`),body=encodeURIComponent(`Hola DIZLE,\n\nMi nombre es ${name}.\nMi email es ${email}.\n\nProyecto o necesidad:\n${message}\n\nSaludos.`);location.href=`mailto:dizle@gestordetareas.com.ar?subject=${subject}&body=${body}`});
document.querySelector('#year').textContent=new Date().getFullYear();